### ISSUE TITLE
Presented view controller captures gestures 

### ISSUE THREAD

**Issue by cameroncooke** [Babylonpartners/DrawerKit#29]
Using DrawerKit to present a `UICollectionView` or `UITableView` controller means that the presented controller captures touches and prevents being able to pull the draw up/down. In the Apple Maps example, touches are ignored by the table view until the draw is 100%.

**Comment by wltrup** [comment]
Yes, that's something we plan to address soon. It's not entirely clear that it should be fixed within `DrawerKit`, as opposed to in the presented view controller.

**Comment by RuiAAPeres** [comment]
@cameroncooke I think the behaviour you want, as @wltrup said, should be provided by you. Looking at the public api:

```swift
public protocol DrawerAnimationParticipant: class {
    /// An instance vended by the conforming object, containing the closures for
    /// preparing, animating along, and cleaning up before, during, and after a
    /// drawer transition animation.
    var drawerAnimationActions: DrawerAnimationActions { get }
}
```

[At preparing](https://github.com/Babylonpartners/DrawerKit/blob/e7782c1978fb5c0ebfe19c7364a23f2d99115b8e/DrawerKit/DrawerKit/Public%20API/Structs/DrawerAnimationActions.swift#L26):

```swift
self.table.viewuserInteractionEnabled = false // from the presented VC.
```

[At clean up](https://github.com/Babylonpartners/DrawerKit/blob/e7782c1978fb5c0ebfe19c7364a23f2d99115b8e/DrawerKit/DrawerKit/Public%20API/Structs/DrawerAnimationActions.swift#L38):

```swift
self.table.viewuserInteractionEnabled = true // from the presented VC.
```

**Comment by wltrup** [comment]
I think @RuiAAPeres's suggestion is a good solution, except that instead of setting `userInteractionEnabled` to `false` and then back to `true`, I'd recommend setting the table view's `panGestureRecognizer.enabled` property to `false` and then back to `true`.
