### ISSUE TITLE
CornerRadius only affecting border, not drawer itself

### ISSUE THREAD

**Issue by Umar-M-Haroon** [Babylonpartners/DrawerKit#67]
I'm playing with the demo app and the corner radius doesn't seem to be affecting the actual VC itself. This is how it looks in the simulator on 11.3 Xcode 9.3.1. Border is there, but it wont affect the drawer itself. Am I missing something?
<img width="547" alt="image" src="https://user-images.githubusercontent.com/3974613/40039543-01d79c4c-57d4-11e8-8df4-b63151c986f2.png">

**Comment by timersha** [comment]
@Umar-M-Haroon, I have the same issue, have you fixed this behavior?

**Comment by Umar-M-Haroon** [comment]
Nope unfortunately I couldn't figure out how to fix this 😞

**Comment by wltrup** [comment]
Hi @Umar-M-Haroon, thanks for your interest in `DrawerKit` and for reporting a bug!

The bug has now been fixed. See [this PR](https://github.com/Babylonpartners/DrawerKit/pull/71) for details.

Once again, many thanks!
