### ISSUE TITLE
Drawer corners are not shown on initial presentation.

### ISSUE THREAD

**Issue by mluisbrown** [Babylonpartners/DrawerKit#87]
On initial presentation, the drawer corners are not displayed. They only appear (and then remain) after moving the drawer:

![drawercorners](https://user-images.githubusercontent.com/4175766/51336800-61780300-1a7d-11e9-8002-52e1995ebe99.gif)

I'm using the following `DrawerConfiguration`:

```swift
DrawerConfiguration(
        fullExpansionBehaviour: .leavesCustomGap(gap: 300),
        cornerAnimationOption: .none,
        handleViewConfiguration: HandleViewConfiguration(autoAnimatesDimming: false)
 )
```

And my `DrawerPresentable` implementation has just the following:

```swift
var heightOfPartiallyExpandedDrawer = CGFloat(200)
```

**Comment by mluisbrown** [comment]
Turns out that in this case the view controller's view `cornerRadius` was being set elsewhere 🤦‍♂️

**Comment by kevinlee-app** [comment]
Hi @mluisbrown , I am also facing this issue. How do you solve this?
On your case, where is the `cornerRadius` set?
