### ISSUE TITLE
None of your spec sources contain a spec satisfying the dependency: `DrawerKit (~> 1.0)`

### ISSUE THREAD

**Issue by jpbonjour** [Babylonpartners/DrawerKit#92]
Installing DrawerKit (0.7.0) version is available only. What happened to 1.0?

**Comment by RuiAAPeres** [comment]
Hi, @jpbonjour thanks for flagging this. We will fix it on Monday. Thanks!

**Comment by andersio** [comment]
The latest release is indeed 0.7.0. We would update the docs. :)
